### ISSUE TITLE
Can not add server

### ISSUE THREAD

**Issue by npendlington** [BarelyMiSSeD/Quake-Live-Rcon#1]
Attempting to add a new local server, the Save button does nothing, and errors are presented. It doesn't seem possible to add a server to the list.

![image](https://user-images.githubusercontent.com/8480122/62957096-08423900-bdec-11e9-8b73-ea29aa78ce14.png)

**Comment by BarelyMiSSeD** [comment]
the IP address needs to be routable. It has been a while since I looked, but I think it won't let the 127.0.0.1 IP address save

**Comment by npendlington** [comment]
Well you're right - it doesn't like the local IP address! Resolved by hosting my QL dedicated server on a VM and connecting to it that way. If you have to use a local server, you can specify the actual IP address of the machine, rather than the loopback IP which also works.
